version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=postgres # Updated password
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "nakama" ]
      interval: 3s
      timeout: 3s
      retries: 5

  nakama:
    container_name: nakama
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:postgres@postgres:5432/nakama && exec /nakama/nakama --name nakama1 --database.address postgres:postgres@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 300
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      builder:
        condition: service_completed_successfully
    volumes:
      - ./data/modules:/nakama/data/modules
    ports:
      - "8349:7349"
      - "8350:7350"
      - "8351:7351"
    healthcheck:
      test: [ "CMD", "/nakama/nakama", "healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5

  builder:
    image: registry.heroiclabs.com/heroiclabs/nakama-pluginbuilder:3.22.0
    working_dir: /workspace
    entrypoint: "/bin/sh"
    command: >
      -c "go build -buildmode=plugin -trimpath -ldflags='-w -s' -o /nakama/data/modules/tictactoe.so /workspace/modules"
    volumes:
      - ..:/workspace
      - ./data/modules:/nakama/data/modules

volumes:
  data:
